/*---------------------------------------------------------------------------------------------
 *  BrightScript Fiddle (https://github.com/lvcabral/brs-fiddle)
 *
 *  Copyright (c) 2023-2026 Marcelo Lv Cabral. All Rights Reserved.
 *
 *  Licensed under the MIT License. See LICENSE in the repository root for license information.
 *--------------------------------------------------------------------------------------------*/
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as fs from "@zenfs/core";
import Toastify from "toastify-js";
import { listFiles, remountFs, resetDom, resetFs, selectorNames } from "./fs-helpers";
import { legacyDataPresent, migrateLegacyStorage } from "../src/legacy-storage";
import {
    isStoragePersistent,
    populateCodeSelector,
    readFileContent,
    saveCodeSnippetMaster,
} from "../src/snippets";

/**
 * A verbatim capture of what ZenFS 1.11.4 wrote to localStorage -- 72-byte inodes and all, which
 * the current 2.5.6 build cannot read. Generated by driving a real 1.11.4 install, not by hand,
 * so this pins the actual on-disk format shipped up to v2.1.7.
 */
const LEGACY_IMAGE: Record<string, string> = JSON.parse(
    readFileSync(resolve(__dirname, "fixtures/zenfs-1.11.4-localstorage.json"), "utf-8")
);

const PNG = [137, 80, 78, 71, 13, 10, 26, 10, 0, 1, 2, 253, 254, 255];

/** Restores a returning user's browser: pre-2.2 snippets sitting in localStorage. */
function seedLegacyStorage() {
    for (const [key, value] of Object.entries(LEGACY_IMAGE)) {
        localStorage.setItem(key, value);
    }
}

function toastTexts(): string[] {
    return vi.mocked(Toastify).mock.calls.map((call) => String(call[0]?.text ?? ""));
}

describe("legacy storage migration", () => {
    beforeEach(async () => {
        await resetFs();
        resetDom();
    });

    describe("detection", () => {
        it("spots the numeric ZenFS 1.x keys", () => {
            expect(legacyDataPresent()).toBe(false);
            seedLegacyStorage();
            expect(legacyDataPresent()).toBe(true);
        });

        it("stays quiet once the marker is set", () => {
            seedLegacyStorage();
            localStorage.setItem("brsFiddle.fsVersion", "2");

            expect(legacyDataPresent()).toBe(false);
        });

        it("ignores the app's own settings keys", () => {
            localStorage.setItem("brsFiddle.state", JSON.stringify({ codeId: "aaaaaaaaaa" }));

            expect(legacyDataPresent()).toBe(false);
        });
    });

    describe("carrying snippets over", () => {
        it("migrates every snippet into the current filesystem", async () => {
            seedLegacyStorage();

            const result = await migrateLegacyStorage();

            expect(result).toEqual({ migrated: 2, persisted: true });
            expect(fs.readdirSync("/code").sort()).toEqual(["aaaaaaaaaa", "bbbbbbbbbb"]);
        });

        it("preserves names, sources and binary files exactly", async () => {
            seedLegacyStorage();
            await migrateLegacyStorage();

            expect(readFileContent("/code/aaaaaaaaaa/.snippet")).toBe("Legacy Draw2D");
            expect(readFileContent("/code/aaaaaaaaaa/source/main.brs")).toContain('print "hi"');

            expect(readFileContent("/code/bbbbbbbbbb/.snippet")).toBe("Legacy SceneGraph");
            expect(readFileContent("/code/bbbbbbbbbb/manifest")).toContain("title=");
            expect(readFileContent("/code/bbbbbbbbbb/components/scene.xml")).toContain("Scene");
            expect([...fs.readFileSync("/code/bbbbbbbbbb/images/logo.png")]).toEqual(PNG);
        });

        it("keeps the full project tree shape", async () => {
            seedLegacyStorage();
            await migrateLegacyStorage();

            expect(listFiles("/code/bbbbbbbbbb")).toEqual([
                ".snippet",
                "components/scene.xml",
                "images/logo.png",
                "manifest",
                "source/main.brs",
            ]);
        });

        it("survives a reload, so the migration is durable in IndexedDB", async () => {
            seedLegacyStorage();
            await migrateLegacyStorage();

            await remountFs();

            expect(readFileContent("/code/bbbbbbbbbb/.snippet")).toBe("Legacy SceneGraph");
            expect([...fs.readFileSync("/code/bbbbbbbbbb/images/logo.png")]).toEqual(PNG);
        });

        it("leaves the old localStorage data in place as a backup", async () => {
            seedLegacyStorage();
            const before = Object.keys(localStorage).filter((k) => /^\d+$/.test(k)).length;

            await migrateLegacyStorage();

            const after = Object.keys(localStorage).filter((k) => /^\d+$/.test(k)).length;
            expect(after).toBe(before);
        });

        it("tells the user what happened", async () => {
            seedLegacyStorage();
            await migrateLegacyStorage();

            expect(toastTexts().join()).toContain("2 code snippet(s) carried over");
        });

        it("makes the snippets show up in the selector", async () => {
            seedLegacyStorage();
            await migrateLegacyStorage();

            populateCodeSelector("");

            expect(selectorNames()).toEqual(["Legacy Draw2D", "Legacy SceneGraph"]);
        });
    });

    describe("running more than once", () => {
        it("sets a marker and does nothing on the next startup", async () => {
            seedLegacyStorage();

            expect((await migrateLegacyStorage()).migrated).toBe(2);
            expect(localStorage.getItem("brsFiddle.fsVersion")).toBe("2");
            expect((await migrateLegacyStorage()).migrated).toBe(0);
        });

        it("does no work at all when there is nothing to migrate", async () => {
            expect(await migrateLegacyStorage()).toEqual({ migrated: 0, persisted: true });
            expect(localStorage.getItem("brsFiddle.fsVersion")).toBeNull();
        });

        it("does not overwrite a snippet already present in the new store", async () => {
            seedLegacyStorage();
            saveCodeSnippetMaster("aaaaaaaaaa", "Already Here", "print 999");

            await migrateLegacyStorage();

            expect(readFileContent("/code/aaaaaaaaaa/.snippet")).toBe("Already Here");
            expect(readFileContent("/code/aaaaaaaaaa/source/main.brs")).toBe("print 999");
            // the other one still comes across
            expect(readFileContent("/code/bbbbbbbbbb/.snippet")).toBe("Legacy SceneGraph");
        });
    });

    describe("when IndexedDB is unavailable", () => {
        it("falls back to an in-memory store and warns, rather than failing to start", async () => {
            const realIndexedDb = globalThis.indexedDB;
            try {
                // Hardened privacy settings and some embedded webviews block IndexedDB.
                vi.stubGlobal("indexedDB", undefined);
                await remountFs();

                expect(isStoragePersistent()).toBe(false);
                expect(toastTexts().join()).toContain("Storage unavailable");

                // the editor still works, it just will not survive a reload
                saveCodeSnippetMaster("dddddddddd", "Session Only", "print 1");
                expect(readFileContent("/code/dddddddddd/source/main.brs")).toBe("print 1");
            } finally {
                vi.stubGlobal("indexedDB", realIndexedDb);
                vi.unstubAllGlobals();
            }
        });

        it("uses IndexedDB and reports persistence when it is available", async () => {
            expect(isStoragePersistent()).toBe(true);
        });

        describe("with snippets that cannot be carried over", () => {
            /** Boots the app's storage the way a browser blocking IndexedDB would. */
            async function startWithoutPersistence() {
                seedLegacyStorage();
                vi.stubGlobal("indexedDB", undefined);
                await remountFs();
                return migrateLegacyStorage();
            }

            it("still surfaces the snippets so the session is usable", async () => {
                try {
                    const result = await startWithoutPersistence();

                    expect(result).toEqual({ migrated: 2, persisted: false });
                    expect(readFileContent("/code/aaaaaaaaaa/.snippet")).toBe("Legacy Draw2D");
                    expect([...fs.readFileSync("/code/bbbbbbbbbb/images/logo.png")]).toEqual(PNG);
                } finally {
                    vi.unstubAllGlobals();
                }
            });

            it("does NOT set the migration marker", async () => {
                try {
                    await startWithoutPersistence();

                    // Setting it here would make a later session with working storage skip the
                    // migration, stranding the snippets in localStorage forever.
                    expect(localStorage.getItem("brsFiddle.fsVersion")).toBeNull();
                    expect(legacyDataPresent()).toBe(true);
                } finally {
                    vi.unstubAllGlobals();
                }
            });

            it("migrates properly on a later run once storage works again", async () => {
                try {
                    await startWithoutPersistence();
                } finally {
                    vi.unstubAllGlobals();
                }

                await remountFs(); // storage available again
                const result = await migrateLegacyStorage();

                expect(result).toEqual({ migrated: 2, persisted: true });
                expect(localStorage.getItem("brsFiddle.fsVersion")).toBe("2");
                await remountFs();
                expect(readFileContent("/code/bbbbbbbbbb/.snippet")).toBe("Legacy SceneGraph");
            });

            it("does not claim the snippets were carried over", async () => {
                try {
                    await startWithoutPersistence();

                    expect(toastTexts().join()).not.toContain("carried over");
                } finally {
                    vi.unstubAllGlobals();
                }
            });
        });
    });

    describe("when it goes wrong", () => {
        it("leaves the marker unset so a fixed build can retry", async () => {
            seedLegacyStorage();
            // Corrupt an inode so the legacy filesystem fails to read.
            for (const key of Object.keys(localStorage).filter((k) => /^\d+$/.test(k))) {
                localStorage.setItem(key, "garbage");
            }

            const result = await migrateLegacyStorage();

            expect(result.migrated).toBe(0);
            expect(localStorage.getItem("brsFiddle.fsVersion")).toBeNull();
            expect(toastTexts().join()).toContain("Could not upgrade previously saved snippets");
        });

        it("keeps the app usable after a failure", async () => {
            seedLegacyStorage();
            for (const key of Object.keys(localStorage).filter((k) => /^\d+$/.test(k))) {
                localStorage.setItem(key, "garbage");
            }

            await migrateLegacyStorage();

            // an empty but working workspace
            expect(() => populateCodeSelector("")).not.toThrow();
            saveCodeSnippetMaster("cccccccccc", "New Code", "print 1");
            expect(readFileContent("/code/cccccccccc/source/main.brs")).toBe("print 1");
        });
    });
});
